#!/bin/bash
# pour générer la vignette

Rscript -e "rmarkdown::render(\"Fantasio.Rmd\", rmarkdown::md_document(preserve_yaml=TRUE, toc=TRUE))"
cp --preserve Fantasio.md ../Fantasio/vignettes/Fantasio.Rmd
rsync -a Fantasio_files ../Fantasio/vignettes/


